version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - default

  vote:
    image: mbaoma/vote-app
    ports:
      - 81:81
    depends_on:
      - redis
    networks:
      - default
  
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  worker:
    image: schoolofdevops/worker:latest
    depends_on:
      - redis
      - db
  
  result:
    image: schoolofdevops/vote-result
    depends_on:
      - db
    ports:
      - 80:80


volumes:
  redis:
    driver: local
  db:
    driver: local
  

networks:
  default:
    driver: bridge   
